### ISSUE TITLE
Motor Lookup & Purchase

### ISSUE THREAD

**Issue by ATATC** [ProjectNeura/LEADS#28]
https://teknic.com/servo-comparison/?gad_source=1&gclid=Cj0KCQiAnfmsBhDfARIsAM7MKi2JHe2fmssby5W0_Xmbsn_AcOIKh3ykKRgjR3_pXT41ztEJVwUvbBwaArNLEALw_wcB

**Comment by qmascarenhas** [comment]
On VeC99 we're using the [Mars 0909 (Etek-R Comparable) Brush-Type Permanent Magnet DC Motor](https://kellycontroller.com/shop/mars-0909/). We have another one of these in stock (purchased last year in anticipation of deployment on VeC 2.0) with a [KDZ - Brushed DC Series/PM Motor Controller (12V-120V) (200A-800A) - 24V, 400A](https://kellycontroller.com/shop/kdz/).

**Comment by qmascarenhas** [comment]
[ME0909 Performance Data](https://villanovaonline.sharepoint.com/sites/VeC2.0DesignTeam/_layouts/OneNote.aspx?id=%2Fsites%2FVeC2.0DesignTeam%2FSiteAssets%2FVeC%202.0%20Design%20Team%20Notebook&wd=target%28_Content%20Library%2FPowertrain%2FVeC99%20Powertrain%20Specs.one%7C6448C79E-8797-4E84-967F-3A4C615DD18C%2FDC%20Motor%20%28ME0909%5C%29%20Performance%20Data%7CED245560-A834-4A2C-84F9-75907BED2D4D%2F%29
onenote:https://villanovaonline.sharepoint.com/sites/VeC2.0DesignTeam/SiteAssets/VeC%202.0%20Design%20Team%20Notebook/_Content%20Library/Powertrain/VeC99%20Powertrain%20Specs.one#DC%20Motor%20(ME0909)%20Performance%20Data&section-id={6448C79E-8797-4E84-967F-3A4C615DD18C}&page-id={ED245560-A834-4A2C-84F9-75907BED2D4D}&end). The 12-V podium finishing cars are running just under 30km/h (~1km race course). Assume about double the speed at 24-V however while this might be the top speed, the average speed is much lower because the race course is the same and the speed in corners is about the same as the 12-V in order to keep the wheels on the ground.
If we’re looking at a different motor, we should be looking at one that beats the ME0909 spec.
I think going brushless would be better but need to find the right motor and controller pairing.
A hub motor would be ideal but those stock motors usually don’t come spec’d at anything lower than 36V so some real electrical design work needs to be done.

**Comment by ATATC** [comment]
The KDZ looks good. We can try that first. I think the J1 or J2 port is common among different motors. But unfortunately, I haven't dealt with either of these controlling methods. It may take extra time to research how to signal it through the Raspberry Pi, or we can ask for help from the community.

**Comment by ATATC** [comment]
I've noticed that in the description it says "Brake switch is used to start regen".

**Comment by ATATC** [comment]
Which motor have we decided to use? @qmascarenhas

**Comment by qmascarenhas** [comment]
@ATATC For the rear drive we're going to go with the PM brushed Motenergy ME0909 with a Kelly KDZ24401 controller. We're running out of time to do any work on researching brushless motors - so we'll keep that work for next year in addition to using the front wheels with regen hubs. The regen hubs will require some additional electrical research which lines up well with AP Physics 2 - so a good "little" (not really little) application project for those of you in grade 11 taking AP Physics 2 next year.

**Comment by ATATC** [comment]
Is that PWM driven?

**Comment by qmascarenhas** [comment]
yes based on a 0-5V DC level from the throttle.

**Comment by ATATC** [comment]
It's labeled as 0-5V analog input in the user manual. Do we have an oscilloscope to check whether is uses PWM?

**Comment by qmascarenhas** [comment]
The PWM is done by the controller; the input control for the PWM is the 0-5V DC level from the throttle based on throttle position (TP).

**Comment by ATATC** [comment]
We need to design a simple RC low pass filter to convert the PWM output from the Raspberry Pi to an analog voltage.

**Comment by qmascarenhas** [comment]
I think you are now working on the Experimental Control System phase of LEADS. We should have a meeting to discuss this at a top level first before you start coding anything please.

**Comment by ATATC** [comment]
We can do it tmr.
