### ISSUE TITLE
2024 August VeC SC Meeting

### ISSUE THREAD

**Issue by ATATC** [ProjectNeura/LEADS#316]
This thread records the 2024 August VeC Steering Council Meeting (@ProjectNeura/vec-steering-council).

**Comment by ATATC** [comment]
## Key Updates

- Video support
  - Multiple cameras
  - Streaming
  - Recording and extracting
  - Replaying
- AI support
- LEADS VeC Data Processor

**Comment by qmascarenhas** [comment]
@ATATC Here's a link to the UofT Formula SAE Electric racing team: [https://fsaeutoronto.ca/](https://fsaeutoronto.ca/). You will notice they are also doing autonomous drive.

**Comment by ATATC** [comment]
![image](https://github.com/user-attachments/assets/28f15ffa-148b-460d-b150-f3623c9ca503)
![image](https://github.com/user-attachments/assets/66d084fe-8c58-438d-b3dc-5828c52ee872)

**Comment by ATATC** [comment]
A Raspberry Pi 5 is better for us because the CPU on the Nvidia Jetson is worse than the Pi, and Pillow does not use GPU.

**Comment by qmascarenhas** [comment]
This should be one of the questions we can solicit some advice for from @LunjunZhang and @MollieBianchi.

**Comment by ATATC** [comment]
https://github.com/geerlingguy/sbc-reviews

**Comment by ATATC** [comment]
## Task Board
1. Get another Arduino Micro - #393
2. Get the accelerometer soldered - #91
3. Get the Orange Pi
4. Reinstall everything
5. Collect data

**Comment by ATATC** [comment]
@aforti86 Hi sir, could you please post the data recorded here?

**Comment by aforti86** [comment]
Here they are. I'll upload some more tonight. I'll try to separate it out by driver tonight to have better separation instead of just random breaks.  
[2024-10-02_15-17-36.csv](https://github.com/user-attachments/files/17248069/2024-10-02_15-17-36.csv)
[2024-10-02_15-28-49.csv](https://github.com/user-attachments/files/17248070/2024-10-02_15-28-49.csv)
[2024-10-02_15-38-20.csv](https://github.com/user-attachments/files/17248071/2024-10-02_15-38-20.csv)
